// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {config} from '../models';
import {service} from '../models';

export function CreateConfig(arg1:model.RouteConfig):Promise<void>;

export function DeleteConfig(arg1:number):Promise<void>;

export function GetArrivals(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<Record<string, any>>;

export function GetCollectionStatus():Promise<boolean>;

export function GetConfigs():Promise<Array<model.RouteConfig>>;

export function GetRouteStations(arg1:string,arg2:string):Promise<Array<model.RouteStation>>;

export function GetSettings():Promise<config.AppSettings>;

export function GetStationRoutes(arg1:string,arg2:string):Promise<Array<service.StationRouteInfo>>;

export function GetTrip(arg1:number):Promise<Array<model.BusArrivalWithConfig>>;

export function SearchRoutes(arg1:string):Promise<Array<model.RouteInfo>>;

export function SearchStations(arg1:string):Promise<Array<model.StationInfo>>;

export function SelectFolder():Promise<string>;

export function StartCollection():Promise<void>;

export function StopCollection():Promise<void>;

export function ToggleConfig(arg1:number,arg2:boolean):Promise<void>;

export function UpdateSettings(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number):Promise<void>;
