// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConfig(arg1) {
  return window['go']['main']['App']['CreateConfig'](arg1);
}

export function DeleteConfig(arg1) {
  return window['go']['main']['App']['DeleteConfig'](arg1);
}

export function GetArrivals(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetArrivals'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetCollectionStatus() {
  return window['go']['main']['App']['GetCollectionStatus']();
}

export function GetConfigs() {
  return window['go']['main']['App']['GetConfigs']();
}

export function GetRouteStations(arg1, arg2) {
  return window['go']['main']['App']['GetRouteStations'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStationRoutes(arg1, arg2) {
  return window['go']['main']['App']['GetStationRoutes'](arg1, arg2);
}

export function GetTrip(arg1) {
  return window['go']['main']['App']['GetTrip'](arg1);
}

export function SearchRoutes(arg1) {
  return window['go']['main']['App']['SearchRoutes'](arg1);
}

export function SearchStations(arg1) {
  return window['go']['main']['App']['SearchStations'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartCollection() {
  return window['go']['main']['App']['StartCollection']();
}

export function StopCollection() {
  return window['go']['main']['App']['StopCollection']();
}

export function ToggleConfig(arg1, arg2) {
  return window['go']['main']['App']['ToggleConfig'](arg1, arg2);
}

export function UpdateSettings(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateSettings'](arg1, arg2, arg3, arg4, arg5);
}
